### ISSUE TITLE
Problem when injecting Mock<ADbContext> with Autofixture

### ISSUE THREAD

**Issue by alandecastros** [MichalJankowskii/Moq.EntityFrameworkCore#33] opened 2023-08-07 22:13 UTC
Hi! 
I'm facing some issues when trying to inject the Mock object of the DbContext in my test Theory.

```
    [Theory]
    [AutoMoqData]
    public async Task Does_Not_Work(
        string chaveNovoAvaliador,
        [CollectionSize(1)] List<AvaliacaoEconomicaModel> avaliacoesEconomicas,
        [Frozen] Mock<AppDbContext> mockDbContext,
        DelegarAvaliacaoEconomicaCommandHandler sut)
    {
        // Arrange
        avaliacoesEconomicas.First().TipoStatusAvaliacaoEconomica = TipoStatusAvaliacaoEconomicaEnum.EmAvaliacao;

        mockDbContext.Setup(x => x.Set<AvaliacaoEconomicaModel>())
            .ReturnsDbSet(avaliacoesEconomicas);

        mockDbContext.Setup(x => x.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .Returns(Task.FromResult(1));

        // Act
        await sut.Handle(new DelegarAvaliacaoEconomicaCommand
        {
            CodigoAvaliacaoEconomica = avaliacoesEconomicas.First().Codigo,
            ChaveAvaliador = chaveNovoAvaliador
        }, default);

        // Assert
        avaliacoesEconomicas.First()
            .ChaveAvaliador
            .Should()
            .Be(chaveNovoAvaliador);
    }
```

This first example returns the following error

```
Message: 
System.InvalidOperationException : No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

  Stack Trace: 
DbContextServices.Initialize(IServiceProvider scopedProvider, DbContextOptions contextOptions, DbContext context)
DbContext.get_ContextServices()
DbContext.get_InternalServiceProvider()
DbContext.get_DbContextDependencies()
DbContext.Set[TEntity]()
DelegarAvaliacaoEconomicaCommandHandler.Handle(DelegarAvaliacaoEconomicaCommand request, CancellationToken cancellationToken) line 26
DelegarAvaliacaoEconomicaCommandHandlerTests.Does_Not_Work(String chaveNovoAvaliador, List`1 avaliacoesEconomicas, Mock`1 mockDbContext, DelegarAvaliacaoEconomicaCommandHandler sut) line 33
--- End of stack trace from previous location ---
```

This second example works fine!

```
    [Theory]
    [AutoMoqData]
    public async Task Works(
        string chaveNovoAvaliador,
        [CollectionSize(1)] List<AvaliacaoEconomicaModel> avaliacoesEconomicas,
        [Frozen] Mock<AppDbContext> mockDbContext)
    {
        // Arrange
        avaliacoesEconomicas.First().TipoStatusAvaliacaoEconomica = TipoStatusAvaliacaoEconomicaEnum.EmAvaliacao;

        mockDbContext.Setup(x => x.Set<AvaliacaoEconomicaModel>())
            .ReturnsDbSet(avaliacoesEconomicas);

        mockDbContext.Setup(x => x.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .Returns(Task.FromResult(1));

        var sut = new DelegarAvaliacaoEconomicaCommandHandler(mockDbContext.Object);

        // Act
        await sut.Handle(new DelegarAvaliacaoEconomicaCommand
        {
            CodigoAvaliacaoEconomica = avaliacoesEconomicas.First().Codigo,
            ChaveAvaliador = chaveNovoAvaliador
        }, default);

        // Assert
        avaliacoesEconomicas.First()
            .ChaveAvaliador
            .Should()
            .Be(chaveNovoAvaliador);
    }
```

Any idea on what I'm doing wrong?

Regards

**Comment by maik-hasler** [comment] 2023-08-08 07:16
Based on the information provided, I assume the problem lies in how the `DelegarAvaliacaoEconomicaCommandHandler` is instantiated and its dependencies are resolved in the unit test.

In the first unit test, the `DelegarAvaliacaoEconomicaCommandHandler` is not explicitly instantiated with the mocked `AppDbContext`. As a result, the `DelegarAvaliacaoEconomicaCommandHandler` tries to resolve its dependencies, including the `AppDbContext`, using the standard dependency injection mechanism. Since no real database provider has been configured for the test environment, the standard dependency injection mechanism fails to provide a proper `AppDbContext`, leading to the error message:

```System.InvalidOperationException : No database provider has been configured for this DbContext.```

On the other hand, in the second unit test, the `DelegarAvaliacaoEconomicaCommandHandler` is correctly instantiated with the mocked `AppDbContext` passed explicitly. This ensures that the `DelegarAvaliacaoEconomicaCommandHandler` uses the mocked context, which is properly set up for the test, and the test executes without any errors.

With that beeing said, your unit test should look like this:

```
[Theory]
[AutoMoqData]
public async Task Should_Hopefully_Work_Now(
    string chaveNovoAvaliador,
    [CollectionSize(1)] List<AvaliacaoEconomicaModel> avaliacoesEconomicas,
    [Frozen] Mock<AppDbContext> mockDbContext)
{
    // Arrange
    avaliacoesEconomicas.First().TipoStatusAvaliacaoEconomica = TipoStatusAvaliacaoEconomicaEnum.EmAvaliacao;

    mockDbContext.Setup(x => x.Set<AvaliacaoEconomicaModel>())
        .ReturnsDbSet(avaliacoesEconomicas);

    mockDbContext.Setup(x => x.SaveChangesAsync(It.IsAny<CancellationToken>()))
        .Returns(Task.FromResult(1));

    var sut = new DelegarAvaliacaoEconomicaCommandHandler(mockDbContext.Object);

    // Act
    await sut.Handle(new DelegarAvaliacaoEconomicaCommand
    {
        CodigoAvaliacaoEconomica = avaliacoesEconomicas.First().Codigo,
        ChaveAvaliador = chaveNovoAvaliador
    }, default);

    // Assert
    avaliacoesEconomicas.First()
        .ChaveAvaliador
        .Should()
        .Be(chaveNovoAvaliador);
}
```

**Comment by alandecastros** [comment] 2023-08-08 12:07
@maik-hasler Thank you for the response! The thing is that I want to use Autofixture feature to inject the frozen mocked object of `AppDbContext` inside my `DelegarAvaliacaoEconomicaCommandHandler`. 
It works with others injected classes that my handler could have.
Regards!

**Comment by maik-hasler** [comment] 2023-08-08 12:57
@alandecastros Okay I understand. Could you provide the code of the `DelegarAvaliacaoEconomicaCommandHandler`? Do you use EF statements which interacts with the database directly? Methods like `.Include()`, `.ExecuteUpdateAsync()` and many more methods can't be mocked by this packgage.

**Comment by alandecastros** [comment] 2023-08-08 18:39
Hi!

```
public class DelegarAvaliacaoEconomicaCommandHandler : IRequestHandler<DelegarAvaliacaoEconomicaCommand>
{
    private readonly AppDbContext _dbContext;
    private readonly ILogger<DelegarAvaliacaoEconomicaCommandHandler> _logger;

    public DelegarAvaliacaoEconomicaCommandHandler(
        AppDbContext dbContext,
        ILogger<DelegarAvaliacaoEconomicaCommandHandler> logger)
    {
        _dbContext = dbContext;
        _logger = logger;
    }

    public async Task Handle(DelegarAvaliacaoEconomicaCommand request, CancellationToken cancellationToken)
    {
        var avaliacaoEconomica = await _dbContext.Set<AvaliacaoEconomicaModel>()
            .FirstOrDefaultAsync(x => x.Codigo == request.CodigoAvaliacaoEconomica, cancellationToken: cancellationToken)
            ?? throw new BadRequestException("Avaliação econômica não existe");

        avaliacaoEconomica.Delegar(request.ChaveAvaliador);

        await _dbContext.SaveChangesAsync(cancellationToken);
    }
}
```
I've put the logger there to test the Autofxture and it's working fine.

I came out with a solution using another library where it creates an in memory DbContext (not mocked).
Now my test looks like this

```
    [Theory]
    [AutoMoqData]
    public async Task Now_It_Works(
        string chaveNovoAvaliador,
        [CollectionSize(1)] List<AvaliacaoEconomicaModel> avaliacoesEconomicas,
        [Frozen] AppDbContext appDbContext,
        DelegarAvaliacaoEconomicaCommandHandler sut)
    {
        // Arrange
        avaliacoesEconomicas.First().TipoStatusAvaliacaoEconomica = TipoStatusAvaliacaoEconomicaEnum.EmAvaliacao;
        appDbContext.Set<AvaliacaoEconomicaModel>().AddRange(avaliacoesEconomicas);
        appDbContext.SaveChanges();

        // Act
        await sut.Handle(new DelegarAvaliacaoEconomicaCommand
        {
            CodigoAvaliacaoEconomica = avaliacoesEconomicas.First().Codigo,
            ChaveAvaliador = chaveNovoAvaliador
        }, default);

        // Assert
        avaliacoesEconomicas.First()
            .ChaveAvaliador
            .Should()
            .Be(chaveNovoAvaliador);
    }
```

Do you want me to close this issue? I don't know if it's supposed to work with Autofixture. 

Regards!

**Comment by MichalJankowskii** [comment] 2023-08-08 20:37
@maik-hasler Thank you for your support in this question

@alandecastros I will look at it after my holidays.

**Comment by maik-hasler** [comment] 2023-08-09 09:16
@MichalJankowskii I was able to reproduce the error mentioned above. Here a quick link for it: https://github.com/maik-hasler/issue-reproducer/tree/main/issues/Moq.EntityFrameworkCore-33

My guess would still be that the CommandHandler does not use the mocked DbContext or that something is messed up with the setup, because this is what the debugger shows:

![image](https://github.com/MichalJankowskii/Moq.EntityFrameworkCore/assets/83227110/b0d3a029-26fe-4d8b-8624-619b7e02cae2)

I hope that this can help :)

**Closed as completed** 2024-01-27 12:50 UTC
