### ISSUE TITLE
The source 'IQueryable' doesn't implement 'IAsyncEnumerable'

### ISSUE THREAD

**Issue by herrozerro** [MichalJankowskii/Moq.EntityFrameworkCore#27] opened 2023-04-01 14:00 UTC
When trying to use a cancellation token with ToListAsync() on an IQueryable I get the following error. 

There are a few things going on.

Queryable with at least one where clause?  Works
Queryable with no where cluases? Doesn't work
ToListAsync without a Token? Works
ToListAsync with a token?  Doesnt work.

```
The source 'IQueryable' doesn't implement 'IAsyncEnumerable<ClassLibrary1.Person>'. Only sources that implement 'IAsyncEnumerable' can be used for Entity Framework asynchronous operations.
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.AsAsyncEnumerable[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at ClassLibrary1.PersonService.GetPersonsInList(List`1 ids, CancellationToken cancellationToken) in /home/user/RiderProjects/WebApplication1/ClassLibrary1/PersonService.cs:line 20
   at TestProject1.UnitTest1.PersonService_GetPersonsInList_ReturnsList() in /home/user/RiderProjects/WebApplication1/TestProject1/UnitTest1.cs:line 28
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264

```

Here is my sample code

```
Public class PersonService
{
    private readonly MyDbContext _context;
    
    public PersonService(MyDbContext context)
    {
        _context = context;
    }

    public async Task<IEnumerable<Person>> GetPersonsInListQuerableAsync(List<int> ids, CancellationToken cancellationToken)
    {
        var persons = _context.Persons.AsQueryable();
        if (false)
        {
            persons = persons.Where(x => ids.Contains(x.Id));
        }
        var personsResult = await persons.ToListAsync();
        return personsResult;
    }
    
    public async Task<IEnumerable<Person>> GetPersonsInListNoQueryableAsync(List<int> ids, CancellationToken cancellationToken)
    {
        var personsResult = await _context.Persons.ToListAsync();  //Does not work if passed a token
        return personsResult;
    }
}

public class Person
{
    [Key]
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

public class MyDbContext : DbContext
{
    public virtual DbSet<Person> Persons { get; set; }
}

[Fact]
    public async Task PersonService_GetPersonsInListQueryable_ReturnsList()
    {
        //arrange
        Mock<MyDbContext> mockContext = new();
        
        IList<Person> persons = new List<Person>
        {
            new() { Id = 1, FirstName = "John", LastName = "Doe" },
            new() { Id = 2, FirstName = "Jane", LastName = "Doe" }
        };
        
        mockContext.SetupGet(x => x.Persons).ReturnsDbSet(persons);
        PersonService personService = new(mockContext.Object);
        
        CancellationTokenSource cancellationTokenSource = new();
        CancellationToken cancellationToken = cancellationTokenSource.Token;
        
        //act
        var personsResult = await personService.GetPersonsInListQuerableAsync(new List<int> { 1, 2 }, cancellationToken);
        
        //assert
        Assert.Equal(persons.Count, personsResult.Count());
    }
    
    [Fact]
    public async Task PersonService_GetPersonsInListNotQueryable_ReturnsList()
    {
        //arrange
        Mock<MyDbContext> mockContext = new();
        
        IList<Person> persons = new List<Person>
        {
            new() { Id = 1, FirstName = "John", LastName = "Doe" },
            new() { Id = 2, FirstName = "Jane", LastName = "Doe" }
        };
        
        mockContext.SetupGet(x => x.Persons).ReturnsDbSet(persons);
        PersonService personService = new(mockContext.Object);
        
        CancellationTokenSource cancellationTokenSource = new();
        CancellationToken cancellationToken = cancellationTokenSource.Token;
        
        //act
        var personsResult = await personService.GetPersonsInListNoQueryableAsync(new List<int> { 1, 2 }, cancellationToken);
        
        //assert
        Assert.Equal(persons.Count, personsResult.Count());
    }
```

**Comment by MichalJankowskii** [comment] 2023-04-03 08:34
Hi,

I ran your tests and the issue is related to chaining types:
- this code `await _context.Persons.ToListAsync();` works fine because setup `mockContext.SetupGet(x => x.Persons).ReturnsDbSet((persons))` create an object that is also implementing `IAsyncEnumerable` interface
- in case of exception, your code looks like this: `await _context.Persons.AsQueryable().ToListAsync()` - here `AsQueryable()` change object type to `IQueryable` and this interface does not inherit `IAsyncEnumerable`, and you get mentioned exception. 

The library does not generate this kind of error and it cannot be fixed on its level.

Also my observations are a bit different:
- Queryable with at least one where clause? **Doesn't work**
- Queryable with no where cluases? Doesn't work
- ToListAsync without a Token? Works
- ToListAsync with a token? **Works**

The last one - ToListAsync with a token? - if you can provide a test demonstrating failure here, please provide me with a code because it should work. If it does not work, then this is something that I should check.

**Comment by herrozerro** [comment] 2023-04-03 12:25
Thanks for looking at this.  I'll see if I can get my code into a working state ... or rather not a working state.  

Just another question on this, in production the queryable way works. It's only the mocked objects that are failing.  Do you have any idea why?

**Comment by herrozerro** [comment] 2023-04-03 14:34
So here is a question.  If I replace AsQueryable() with a Where(x=>true) it works.  It's doing the same thing, right?  Where() returns an Iqueryable.  But it works in this case.

```
public async Task<IEnumerable<Person>> GetPersonsInListNoQueryableAsync(List<int> ids, CancellationToken cancellationToken)
    {
        var personsResult = await _context.Persons.Where(x=>true).ToListAsync(cancellationToken);
        return personsResult;
    }
```

**Comment by MichalJankowskii** [comment] 2023-04-03 21:17
To find an answer to this question, you need to check the implementation of all methods:
- `ToListAsync` and `AsQueryable` are part of EntityFramework lib
- `Where` is part of Linq

Documentation of `AsQuaryable` says:

> If the type of source implements [IQueryable<T>](https://learn.microsoft.com/en-us/dotnet/api/system.linq.iqueryable-1?view=net-7.0), [AsQueryable(IEnumerable)](https://learn.microsoft.com/en-us/dotnet/api/system.linq.queryable.asqueryable?view=net-7.0#system-linq-queryable-asqueryable(system-collections-ienumerable)) returns it directly. Otherwise, it returns an [IQueryable<T>](https://learn.microsoft.com/en-us/dotnet/api/system.linq.iqueryable-1?view=net-7.0) that executes queries by calling the equivalent query operator methods in [Enumerable](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable?view=net-7.0) instead of those in [Queryable](https://learn.microsoft.com/en-us/dotnet/api/system.linq.queryable?view=net-7.0).

This can be an explanation. 

BTW... I hope you are aware of `ToListAsync` limitations:
>
    ///         Multiple active operations on the same context instance are not supported. Use <see langword="await" /> to ensure
    ///         that any asynchronous operations have completed before calling another method on this context.
    ///         See <see href="https://aka.ms/efcore-docs-threading">Avoiding DbContext threading issues</see> for more information and examples.

**Closed as completed** 2023-04-04 00:56 UTC
